c Glue between proVBFH-cs and the VBFNLO matrix elements of proVBFH
c (option A, docs/DESIGN.md), called without the POWHEG-BOX machinery.
c Momenta p(0:3,6) in the ordering of proVBFH's H+3j Born:
c   1, 2 incoming partons of line 1 and line 2, 3 Higgs,
c   4, 5 outgoing quarks of line 1 and line 2, 6 the extra parton.
c Flavours bflav(6) as in proVBFH's flavour lists (PDG, gluon = 0, the
c Higgs entry is not used).
c---------------------------------------------------------------------
      subroutine cs_init_vbfnlo
      implicit none
      include 'nlegborn.h'
      include 'pwhg_flst.h'
      include 'pwhg_st.h'
      integer j
c     couplings, masses and widths from vbfnlo.input/powheg.input, as in
c     proVBFH
      call init_couplings
c     alpha_s is applied by proVBFH-cs per line (scales per line)
      st_alpha = 1d0
      st_muren2 = 1d4
c     no tags: compborn_hjjj returns both lines, split in born_col(1:2)
      flst_cur_iborn = 1
      do j=1,nlegborn
         flst_borntags(j,1) = 0
      enddo
      end
c---------------------------------------------------------------------
c |M|^2 (averaged over initial spins and colours, alpha_s = 1) of
c q q -> q q g H and crossings, for the extra parton emitted from
c line 1, (p1, p4), and from line 2, (p2, p5).
      subroutine cs_hjjj_lines(p,bflav,m1,m2)
      implicit none
      include 'nlegborn.h'
      double precision p(0:3,nlegborn),m1,m2
      integer bflav(nlegborn)
      double precision born,bmunu(0:3,0:3,nlegborn),
     $     bornjk(nlegborn,nlegborn),borncol(2)
      call calc_als
      call ctrans(1)
      call compborn_hjjj(p,bflav,born,bmunu,bornjk,borncol)
      m1 = borncol(1)
      m2 = borncol(2)
      end
c---------------------------------------------------------------------
c stand-ins for POWHEG-BOX routines referenced by the files above but
c not used by proVBFH-cs
      double precision function pwhg_alphas(q2,xlam,inf)
c     used by convert_coup.f (KOPPLN: running quark masses for the Higgs
c     partial widths, and the HELAS strong coupling, which the VBFNLO
c     Born, real and virtual routines do not use: they take alpha_s from
c     scales.inc, i.e. st_alpha). HOPPET's running coupling, which
c     inclusive_init sets up before cs_init_vbfnlo is called.
      implicit none
      double precision q2,xlam,hoppetAlphaS
      integer inf
      external hoppetAlphaS
      pwhg_alphas = hoppetAlphaS(sqrt(q2))
      end

      double precision function random()
      implicit none
      stop 'proVBFH-cs: random() is not available'
      end

      subroutine pick_random(n,w,iret)
      implicit none
      integer n,iret
      double precision w(n)
      stop 'proVBFH-cs: pick_random is not available'
      end
c---------------------------------------------------------------------
c the VBF Born point generated by the inclusive phase space (gen_phsp):
c momenta (1, 2 incoming, 3 Higgs, 4, 5 outgoing quarks of lines 1, 2),
c momentum fractions, phase-space Jacobian and beam energy squared
      subroutine cs_get_born(p,xb1,xb2,jac,sbeams)
      implicit none
c     the /pwhg_kn/ layout of the inclusive phase space (phase_space.f
c     declares nlegborn = 5; the VBFNLO/POWHEG files use 6 but do not
c     touch /pwhg_kn/)
      integer nlegborn, nlegreal
      parameter (nlegborn = 5)
      parameter (nlegreal = nlegborn + 1)
      include 'pwhg_kn.h'
      double precision p(0:3,5),xb1,xb2,jac,sbeams
      integer j,mu
      do j=1,5
         do mu=0,3
            p(mu,j) = kn_pborn(mu,j)
         enddo
      enddo
      xb1 = kn_xb1
      xb2 = kn_xb2
      jac = kn_jacborn
      sbeams = kn_sbeams
      end
c---------------------------------------------------------------------
c momenta (E,px,py,pz) of n particles (1, 2 incoming, 3 Higgs, the
c rest outgoing partons) into the HEPEVT arrays read by user_analysis
      subroutine cs_fill_phep(n,p)
      implicit none
      include 'hepevt.h'
      integer n,j
      double precision p(0:3,n)
      nhep = n
      do j=1,n
         phep(1,j) = p(1,j)
         phep(2,j) = p(2,j)
         phep(3,j) = p(3,j)
         phep(4,j) = p(0,j)
         phep(5,j) = sqrt(abs(p(0,j)**2-p(1,j)**2-p(2,j)**2
     $        -p(3,j)**2))
         isthep(j) = 1
         if (j.le.2) isthep(j) = -1
         idhep(j) = 0
      enddo
      idhep(3) = 25
      end
c---------------------------------------------------------------------
      subroutine pwhg_exit(i)
c     used by pwhg_bookhist-multi.f on errors
      implicit none
      integer i
      call exit(i)
      end
