######################################################################
# Makefile.inc for proVBFHH
# File generated with:
#  ./configure
######################################################################

# external programs needed
FJEXEC=fastjet-config
LHEXEC=lhapdf-config
HPEXEC=hoppet-config
# general settings 
COMPILER=gfortran
SHELL=/bin/bash
